### ISSUE TITLE
Setting up complete mockrunner project

### ISSUE THREAD

**Issue by joe42** [mockrunner/mockrunner#12]
Hi,

Is there an easy way to set up mockrunner so I can run the tests within eclipse? I am not used to maven. But if it helps me get all dependencies to run the test, that would be nice. 

Joe

**Comment by InfoSec812** [comment]
Not sure what problem you are having, but I run those tests in eclipse
daily. Could you provide more details?

Deven Phillips
from my mobile

**Comment by joe42** [comment]
I create a new maven project, check "Create simple project", and enter group id com.mockrunner  artifact id mockrunner-all. I expected to get a complete working project, but I have the project structure without sources or dependencies.

**Comment by cemartins** [comment]
What best works for me is to use the command line to clone the repository
and then, in eclipse, File / Import / Maven / Existing Maven Project.
For this you have to install Git on your computer from http://git-scm.com/
 or http://msysgit.github.com/; and then execute git clone
https://github.com/mockrunner/mockrunner.git

Hope it helps

**Comment by joe42** [comment]
Thanks, that worked. I tried this before, but as I noticed just now, I forgot to select the pom, so I could not create the project. Very useful, seems like I need to give maven another chance.
