### ISSUE TITLE
mockrunner-all-1.0.6.jar and mockrunner-core-1.0.6.jar

### ISSUE THREAD

**Issue by chrisfw** [mockrunner/mockrunner#14]
FYI, the SHA1 hashes don't match on the jars downloaded from https://oss.sonatype.org/content/groups/public/com/mockrunner.  Please verify they have not been compromised,

**Comment by cemartins** [comment]
Hi. Thank you for the warning.

If you want to validate artifact authenticity use the gpg signatures that all mockrunner releases have as well.

Bugs in Maven 2.1.0 and 2.2.0 result in incorrect hashes .md5 and the .sha1. I am not sure which maven version was used for 1.0.6 deployment, but if the above gpg verification passes, then the jars are good.

**Comment by chrisfw** [comment]
Thanks for the quick response and the information.  That is good to know.

Regards,

Chris
