### ISSUE TITLE
Recieve Timeout / Incompatibility with Spring JmsTemplate.sendAndRecieve

### ISSUE THREAD

**Issue by eriede** [mockrunner/mockrunner#21]
in com.mockrunner.mock.jms.MockMessageConsumer

The following functions return immediately with a null parameter if no messages are in the queue.  

Message receive(long timeout) 
Message receive()

 
This is incorrect operation. (Refrerence: http://docs.oracle.com/javaee/6/api/javax/jms/MessageConsumer.html)  receive(long timeout) should wait for the timeout period, and receive() should wait forever for a message to be returned.  The current implementations act as “RecieveNoWait” should.   

This causes the org.springframework.jms.core.JmsTemplate.sendAndReceive family of functions to operate incorrectly, returning a “null” message, before the message can be responded to.  

I am developing a quick patch to get my project going and will post shortly.

**Comment by cemartins** [comment]
Thank you so much for your help.
I will integrate your pull request when it comes.

kind regards
Carlos

**Comment by eriede** [comment]
The pull request was opened as https://github.com/mockrunner/mockrunner/issues/22

**Comment by cemartins** [comment]
Incorporated your changes and promoted a maven release: mockrunner-1.0.8. It should be available in a couple of hours.
Thanks a lot Edward.
