### ISSUE TITLE
JMSCorrelationID does not work in JMS module

### ISSUE THREAD

**Issue by keilw** [mockrunner/mockrunner#24]
Maybe it is not implemented by **Mockrunner JMS** but even if so, I'd expect it to be ignored (and especially not hang the whole test as in 1.0.8)

It seems, **JMSCorrelationID** does not work in the JMS module.

Code like

```
qrec = session.createReceiver(queue);
Message m = qrec.receive();
```

works assuming a message was sent to the queue first.

Trying 

```
String filter = "JMSCorrelationID = 'myId'";
qrec = session.createReceiver(queue, filter);
Message m = qrec.receive();
```

gives a _null_ message, even if JMSCorrelationID had been set to the message first like

```
msg.setJMSCorrelationID("myId");
```

At least in Mockrunner 1.0.4 it you get null. After upgrading to 1.0.8 the receiver test simply hangs up completely. I suspect it could be related to https://github.com/mockrunner/mockrunner/issues/13 but not sure.

**Comment by cemartins** [comment]
Hi Kellw and thank you for raising this issue.
It would be a great help if you could submit a pull request with a fix.

**Comment by keilw** [comment]
will have a look, so far I only faced it from outside, but try to check it out and test in our environment if i can;-)

**Comment by cemartins** [comment]
Thank you Keilw. Mockrunner survives thanks to you and for you. I do my best to release new versions as soon as new improvements come in.

**Comment by davidkarlsen** [comment]
As far as I can see its working, you can pull this branch for a test for it: https://github.com/davidkarlsen/mockrunner/tree/issue24

**Comment by keilw** [comment]
I may be able to test it, but since we rely on Maven a lot, I'd probably have to do a temporary build of that branch in our local Maven repo;-)

**Comment by davidkarlsen** [comment]
You don´t need to build anything - what I am saying is that I am not able to reproduce your issue:
https://github.com/davidkarlsen/mockrunner/commit/d5db61aa7b4421c0e22661eb449d0c59a6a1baa7

As for the build you can see here: https://travis-ci.org/davidkarlsen/mockrunner/builds/70552148

**Comment by keilw** [comment]
However, the test hangs forever against 1.0.8, so while I may be able to use the test snippet, the problem does occur. I can't share the test due to dependencies on project internals, but one big difference is using BytesMessage instead of TextMessage for starters.

**Comment by cemartins** [comment]
2.0.4 released
