### ISSUE TITLE
Introducing Java 5 Generics

### ISSUE THREAD

**Issue by kz282** [mockrunner/mockrunner#25]
Hello Guys!

Thanks for maintaining this project, I found it very-very useful in my work.

One day I was trying to change the ResultSet of a Prepared statement, and I failed. I created the Prepared Statement like this:
```
    PreparedStatementResultSetHandler preparedStatementResultSetHandler = 
        conn.getPreparedStatementResultSetHandler();
        
    MockResultSet resultSet = preparedStatementResultSetHandler.createResultSet();
    for(String columnName : columnNames){
        resultSet.addColumn(columnName);
    }
    for(Object[] row : rows){
        resultSet.addRow(row);
    }
    preparedStatementResultSetHandler.prepareResultSet(query, resultSet, new Object[0]);
```
And I tried to remove the ResultSet as follows:
```
    PreparedStatementResultSetHandler preparedStatementResultSetHandler = 
        conn.getPreparedStatementResultSetHandler();
    preparedStatementResultSetHandler.removeResultSet(query);
```

I found out that the PreparedStatementResultSetHandler.removeResultSet(String sql) does not remove the result set. Debugging further it seems that AbstractParameterResultSetHandler and AbstractResultSetHandler have some private fields with the same name and the removeResultSet(String sql) operates on the AbstractResultSetHandler.resultSetsForStatement, but not on AbstractParameterResultSetHandler.resultSetsForStatement. Those Maps have different value types too.

The simple solution would be adding overriding methods to AbstractParameterResultSetHandler, but that's still an error-prone solution. The fields that have the same name in AbstractParameterResultSetHandler and AbstractResultSetHandler are to be fixed. I was thinking to introduce Java 5 style Generics to the source to make sure that Maps and Lists are handled properly. I think that #11 would be resolved by this too.

But before starting that I would like to ask if someone has started that work before. Is there anyone still using Java 1.4?

Kind regards,
KZ

**Comment by cemartins** [comment]
I suggest with make a branch - call it Java1.4, and move ahead to java 5 and later on the master branch.

**Comment by InfoSec812** [comment]
Agreed!

**Comment by cemartins** [comment]
Ok. I did the branch and also deleted the old java 1.3 and 1.4 modules from the master.
Go for it KZ

**Comment by kz282** [comment]
I have made the first commit to my fork. I ran into trouble with the CallableStatement handling, as CallableStatements can have indexed and named parameters. It means I can't put them simply into a `Map<Integer, Object>` or `Map<String, Object>`. That part needs a bit of thinking.

I have cleaned some parts where methods returned `something` or `something[]` as `Object`.

**Comment by kz282** [comment]
Hello Guys,

I have made the changes I wanted in my last two commits: I reworked the fields of `AbstractParameterResultSetHandler` and `AbstractResultSetHandler`. Now prepared statements without parameters and non-prepared statements work the same way.

#11 is fixed, #25 is fixed.

The collections were updated to Java 1.5 style generics everywhere in Mockrunner-JDBC.

Please check the changes in my fork and reply!

**Comment by cemartins** [comment]
Hi KZ,

Thanks for the improvement.
It would be better if you did a pull request. I can easily test and then merge your changes.

**Comment by kz282** [comment]
Ok, I have done the pull request. I will be available to discuss the changes if you would like.

**Comment by cemartins** [comment]
Hi KZ,

thank you very much for your contribution. I made a real else which already includes your changes. You can find it on maven central. Example: http://search.maven.org/#search%7Cga%7C1%7Ca%3A%22mockrunner-jdbc%22

**Comment by kz282** [comment]
Thanks a lot, and it was nice to be able to help.
