### ISSUE TITLE
JMS Test Module should create Queues/Topics automatically

### ISSUE THREAD

**Issue by greyfairer** [mockrunner/mockrunner#30]
In activeMQ, JMS Queues and Topics are created automatically when first used.

Mockrunner JMS does not do this, so when you use it in a test, you need to explicitly create all the queues and topics you are going to use.

A simple lazy initialization like creating the topic on the first call of DestinationManager.getTopic() could solve a lot of overhead for tests.

**Comment by cemartins** [comment]
Fixed with pull request from greyfairer

**Comment by cemartins** [comment]
Fix available in new release mockrunner-1.1.1
