### ISSUE TITLE
/src/test/java/com/mockrunner/jms/BasicJMSTestCaseAdapter.java should be in /src/main/java/... ?

### ISSUE THREAD

**Issue by The-Alchemist** [mockrunner/mockrunner#34]
Shouldn't `/src/test/java/com/mockrunner/jms/BasicJMSTestCaseAdapter.java` be in `/src/main/java/...` so it can be included in the JMS module JAR?

Thanks!

**Comment by alan125** [comment]
Shouldn't this be closed now since code was merged?

**Comment by cemartins** [comment]
Yep. You're right :)
