### ISSUE TITLE
Generics for servlet creation

### ISSUE THREAD

**Issue by cristcost** [mockrunner/mockrunner#38]
Hi,

I would like to use generics for the `com.mockrunner.servlet.ServletTestModule.createServlet(Class)` method and then on the corresponding `com.mockrunner.servlet.BasicServletTestCaseAdapter.createServlet(Class)` 

That is, I would like to have the source changed into the following code:

```
    public <T extends HttpServlet> T createServlet(Class<T> servletClass)
    {
        if(!HttpServlet.class.isAssignableFrom(servletClass))
        {
            throw new RuntimeException("servletClass must be an instance of javax.servlet.http.HttpServlet");
        }
        try
        {
            T theServlet = servletClass.newInstance();
            setServlet(theServlet, true);
            return theServlet;
        }
        catch(Exception exc)
        {
            throw new NestedApplicationException(exc);
        }
    }
```

and

```
  protected <T extends HttpServlet> T createServlet(Class<T> servletClass)
  {
      return servletTestModule.createServlet(servletClass);
  }
```

Benefits:
no need to cast the return type to my servlet in tests:
`MyServlet servlet = (MyServlet) createServlet(MyServlet.class);`
becomes
`MyServlet servlet = createServlet(MyServlet.class);`

also, the method become type safe, any invocation will be with a class that is subclass of HttpServlet, so the check `if(!HttpServlet.class.isAssignableFrom(servletClass))` becomes quite reduntant

**Comment by cemartins** [comment]
Hi there,

Thanks for writing. You can contribute to Mockrunner with pull requests. A pull request with the Servlet Generics would be very welcome.

Your main challenge would be bringing Mockrunner to Java 8 (or at least Java7) to support generics, I think.
Could you do that?

**Comment by alan125** [comment]
@cemartins Generics is available since Java 5

**Comment by alan125** [comment]
Shouldn't this be closed now since code was merged?

**Comment by cemartins** [comment]
Absolutely
