### ISSUE TITLE
Unable to use columnType

### ISSUE THREAD

**Issue by lwhite1** [mockrunner/mockrunner#39]
My application needs to use the ResultSetMetaData.getColumnType(), but it returns 1111 (SQL type "other") for any column type. This would be a nice addition if it could be done. 

```
MockResultSet rs = new MockResultSet("myMock");
rs.addColumn("columnA", new Integer[]{1});
rs.getMetaData.getColumnType(1) // returns 1111
```

**Comment by kz282** [comment]
Hello!

Currently you have to fill ResultSetMetaData manually or via MockResultSet.setResultSetMetaData(ResultSetMetaData). Mockrunner-JDBC does not try to determine column types from the types of the objects to be returned.

        ResultSetMetaData metaData = rs.getMetaData();
        if(metaData instanceof MockResultSetMetaData){
            ((MockResultSetMetaData)metaData).setColumnType(1, Types.VARCHAR);
        }

**Comment by InfoSec812** [comment]
I agree that it would be ideal to support this in an "automagic" fashion as possible. We could have a "default" based on the type provided and allow it to be overridden when desired. I will mark this for the 2.0.0 release milestone.

**Comment by cemartins** [comment]
Issue fixed with release
