### ISSUE TITLE
Servlet 3.1 compatibility

### ISSUE THREAD

**Issue by BrynCooke** [mockrunner/mockrunner#4]
I know this is a big job, but just wondering if it is in the works?

**Comment by Johnlon** [comment]
+1

**Comment by InfoSec812** [comment]
@justinpitts and I will be having a look at this for the 2.0.0 milestone. We will be updating the project to work with Java 8 and trying to implement support for newer specs.

**Comment by cemartins** [comment]
Cleanup issues after 2.0.4 released
