### ISSUE TITLE
MockResultSet: need a better way to add rows

### ISSUE THREAD

**Issue by DwordPtr** [mockrunner/mockrunner#41]
I'm testing a legacy application and have to mock a ResultSet that's quite wide for which adding rows by creating `List<Object>` is unreadable. Is there anyway to create a` Map<String,Object> row`  for something like  `mockResultSet.addRow(row);` where the keys are the column names and the Object is the column's contests?

**Comment by cemartins** [comment]
The project is open to nice feature contributions like that one. It would be great if you gave us a pull request.

**Comment by DwordPtr** [comment]
Sounds like something I could do.

**Comment by DwordPtr** [comment]
https://github.com/mockrunner/mockrunner/pull/42
