### ISSUE TITLE
Catching up

### ISSUE THREAD

**Issue by justinpitts** [mockrunner/mockrunner#51]
I'd like to tackle some of the larger issues I see, especially the ones centered around JMS.

As a means to that end, I'd like to make some passes over the codebase to "catch up" to Java 7, primarily with respect to being precise about type parameters. I'd also like to clean up the usual warnings around serial version uids, the Override annotation, et cetera. My goal would be to get to as close to zero warnings as possible.

Before I get deep in that effort, is there any concern or hesitation about that?

**Comment by InfoSec812** [comment]
My only concern here is that if we start updating for Java 7, are we going to put out some users who are still tied to Java 6? I know that Java 6 is EOL, so perhaps that is not such a big concern.

**Comment by justinpitts** [comment]
The pom needs to faithfully reflect the java version we intend to support,
and not only is java 6 EOL, but so is 7.

**Comment by InfoSec812** [comment]
Having just come from a conference where MANY people admitted to still supporting Java 1.5, EOL may not be the end-all-be-all of making a decision.

**Comment by InfoSec812** [comment]
I'm going to try to find a way to reach out to our users and see if we can get some feedback on this. I would personally LOVE it if we could move toward Java 8 support in order to serve the current needs of the community, but I need to be mindful of where our current users stand on such an endeavor.

**Comment by justinpitts** [comment]
Are our users needing source or binary compatibility?

**Comment by InfoSec812** [comment]
That is a good question, and I don't have an easy way to judge that. Perhaps the right answer is to start work on a new branch for what we will call "2.0" and aim for Java 7 (or even 8) as the target. Then, we can put 1.x into maintenance as a branch with "Best effort" support so that we do not break things for legacy users.

**Comment by justinpitts** [comment]
> Perhaps the right answer is to start work on a new branch for what we will call "2.0" and aim for Java 7 (or even 8) as the target. 

I like that idea a great deal, especially considering the newer API versions that are being requested. I'm happy to take that on. My vote would be for JDK 8.

**Comment by InfoSec812** [comment]
OK, I have created a new branch "1.x_maintenance" where we will provide "best effort" support for legacy versions of the JVM (<1.7). I have updated the POMs for all projects to version 2.0.0-SNAPSHOT for future work. Please feel free to proceed working on the assumption that the 2.x series will support Java >= 8

**Comment by InfoSec812** [comment]
Please keep in mind that all PRs should be limited in scope for tracking and review purposes. And thanks again for all of the assistance!

**Comment by justinpitts** [comment]
Please help me understand, as well as you can, what 'limited in scope' means for you, so that I can abide by a common understanding.

**Comment by InfoSec812** [comment]
As much as possible, I would prefer to not have to review PRs which are hundreds of lines in length. Sometimes there really is no option, but try to avoid onerous reviews which could be difficult to understand and push through quickly.

**Comment by justinpitts** [comment]
Thats completely understandable.

A great deal of the issues I'd like to resolve have simple resolutions, but they of course involve hundreds or even thousands of lines.

It seems to me that one way to approach that is to dedicate one PR to a specific kind of fix, in a single subproject. This will somewhat limit the number of changes per PR, and make them easier to digest because they all ought to be the same kind of change.

**Comment by InfoSec812** [comment]
Sounds like a perfect approach!
