### ISSUE TITLE
Licenses

### ISSUE THREAD

**Issue by hrieke** [mockrunner/mockrunner#57]
Can you please move the licenses to the individual projects / headers of the projects.  By dumping all of the licenses in the root folder you have made it extremely difficult to tell which code (and snippet) is under which license.

Thanks

**Comment by InfoSec812** [comment]
The Mockrunner code itself if under the Apache License, but the other license files are there for libraries which are used in the project. They apply to multiple subprojects and as such I am reluctant to copy them to the appropriate subprojects as they would probably end up in all of them anyhow.

**Comment by hrieke** [comment]
Then perhaps a file listing the licenses with which files / subprojects?
In anycase, as an end-user using your software, I would worry that I am not following license terms.

**Comment by cemartins** [comment]
Closing due to lack of followup.
