### ISSUE TITLE
Servlet - Upload file test example

### ISSUE THREAD

**Issue by atilacamurca** [mockrunner/mockrunner#60]
Are there any examples of testing upload files with Servlets? Is that even possible with Mockrunner?

**Comment by cemartins** [comment]
Hi Átila,

Thank you for your message.

As far as I know mockrunner servlet does not support file upload.

Sorry about the lack of information. I’m just the guy who brought mockrunner to maven and to github. I used the jms module for a while but that was it.

It would be great if people like you would join in and improve mockrunner on the modules they like. I’ll be very happy to accept pull requests 😀

Kind regards
Carlos.

**Comment by atilacamurca** [comment]
Are there any directions about the implementation?

**Comment by cemartins** [comment]
Yes: don’t break the unit tests

**Comment by cemartins** [comment]
No contribution received
