### ISSUE TITLE
MR-jdbc does not return subsequent resultsets for a query

### ISSUE THREAD

**Issue by kz282** [mockrunner/mockrunner#71]
Hello!

I am testing an app where I would like to return different resultsets for subsequent calls of the same query. I am experimenting with MockPreparedStatements.prepareResultSets(String sql, MockResultSet[] resultSets), but after executing the query I'm always receiving the first MockResultSet. Why is it possible to configure multiple resultsets then?

I think I have a clue about this:
```
    private MockResultSet cloneAndSetMultipleResultSets(MockResultSet[] results, MockParameterMap params)
    {
        results = cloneResultSets(results);
        if(null != results)
        {
            resultSetHandler.addReturnedResultSets(results);
        }
        setResultSets(results);
        setGeneratedKeysResultSet(sql, params);
        if(null != results && results.length > 0)
        {
            return results[0];
        }
        return null;
    }
```
Are there any reasons, why results[0] is returned every time, or is this a bug?

I think if there are multiple resultsets for a given query and parametermap, the first resultset is to be returned for the first execution, the second for the second etc. If there are more executions than resultsets, then the last resultset is to be returned multiple times. This usage is consistent with the "same resultset every time the query is executed with a parameter map" use case as well.

**Comment by cemartins** [comment]
Hi KZ, 
Thanks for writing. I am not actively developing this project anymore, but if you make a pull request that fixes it, I will gladly merge it and make a new release with your changes.

**Comment by kz282** [comment]
Hi!

After reviewing the PreparedStatement documentation, I found out that I missed the point. I am closing this issue...

**Comment by NicklasWallgren** [comment]
@kz282 How did you solve this issue?

**Comment by kz282** [comment]
Hello Nicklas,
As far as I remember I removed the resultset and added a new one. But after some time I decided to go with a proper database in Docker. I advise you to try Testcontainers. If you can create an image preloaded with your database schema then a testcontainer can be launched in seconds.

**Comment by NicklasWallgren** [comment]
> Hello Nicklas, As far as I remember I removed the resultset and added a new one. But after some time I decided to go with a proper database in Docker. I advise you to try Testcontainers. If you can create an image preloaded with your database schema then a testcontainer can be launched in seconds.

Thanks for the reply!

> I advise you to try Testcontainers.

That's my usual approach - but for this particular case I'll need to mock an old stored procedure located in a DB2 database, which I can't spin up in a docker container.
