### ISSUE TITLE
Dependency structure when using MockRunner (changed in 2.0.3)

### ISSUE THREAD

**Issue by mthmulders** [mockrunner/mockrunner#74]
First of all, thanks for making and maintaining MockRunner! It's been valuable to me in the past and I hope it will continue to be.

I have a few projects where I use MockRunner Servlet. Using Maven, I pull in MockRunner Servlet, and that would pull in MockRunner Core. I'm not sure if this is the intended way of using it, but the documentation doesn't really point out how it should be done alternatively.

Starting with MockRunner 2.0.3, this approach is no longer sufficient. I also **need** to have a dependency on MockRunner Core. I came across this because Dependabot suggested to upgrade and that branch suddenly didn't work anymore. This change has been introduced in #67, where all modules that depend on Core where updated to have `<scope>provided</scope>`. This requires dependant projects (like mine) to provide for that dependency.

If this is the intended behaviour, it might be nice to have that somewhere on the MockRunner website. I could provide a PR with some documentation suggestion. If it is not intended, I could provide a PR that undoes the `<scope>provided</scope>`.

Please let me know what approach fits best :-)

**Comment by cemartins** [comment]
Hi Maarten,

First of all thank YOU for showing an interest about mockrunner. If it weren’t for people like you, it would be dead a long time ago, I think.
To be honest, I needed it - the jms module, a long time ago. The project was not a maven project yet.
I asked the original guys who created it about moving to maven and they asked me to do it myself. That’s how it ended up on github as a maven project. But nowadays I just maintain it and create new releases when there are changes. I don’t use it myself anymore.
Regarding your question, I think the “provided” may be wrong for most modules. Clearly for the servlet it is.
If you make a pull request I’ll merge it and release it. And if you want I can add you to the team of maintainers too.

**Comment by mthmulders** [comment]
I don't use it that often, only in the two pet projects that now refer to this issue. So I don't really know the code base very well. So promoting me to maintainer would be too much honour, I guess.

As far as I can tell, I would expect all modules to have a dependency on the "Core" module since that has the shared code. That should not be a "provided" dependency, since it would mean that whoever uses the JMS module must manually provide the "Core" module as well. Instead, it would make sense to use Mavens dependency resolution and collection mechanisms for that.

I would propose to put `com.mockrunner:mockrunner-core` in the Dependency Management section of the "root" POM with `<version>${project.version}</version>`. All other modules could then have a dependency on `com.mockrunner:mockrunner-core` _without_ a version or scope, and Maven would automatically resolve that to the same version as that module that was pulled in by whoever uses MockRunner.

In this setup, those who use OSGi can still use MockRunner by pulling in the module(s) that they need.

**Comment by cemartins** [comment]
Thanks for your contribution.
Your changes has been released now.
