### ISSUE TITLE
Contribution: XMLResultSetFactory for Oracle SQL Developer export format

### ISSUE THREAD

**Issue by achimwestermann** [mockrunner/mockrunner#78]
I just paste in the source file. It allows you export query results from your database with oracle sql developer tool  (https://www.oracle.com/tools/downloads/sqldev-downloads.html). We use it to get test data from our real world databases. Thx for the great project!
Achim

-----------------------------
 package com.mockrunner.jdbc;

import java.io.File;
import java.util.Iterator;
import java.util.List;

import org.jdom.Document;
import org.jdom.Element;
import org.jdom.input.SAXBuilder;

import com.mockrunner.base.NestedApplicationException;
import com.mockrunner.mock.jdbc.MockResultSet;

/**
 * Adds support for the XML export format that Oracle SQLDeveloper (at least version 17.2.0.188) creates.
 * See https://www.oracle.com/tools/downloads/sqldev-downloads.html 
 * <p>
 * <b>Example format:</b>
 * 
 * <pre>
 * <RESULTS>
 *   <ROW>
 *     <COLUMN NAME="CONNECTION_NO"><![CDATA[2517308732]]></COLUMN>
 *     <COLUMN NAME="VAR"><![CDATA[chatservice.platformid]]></COLUMN>
 *     <COLUMN NAME="VALUE"><![CDATA[QDE]]></COLUMN>
 *     <COLUMN NAME="VALID_FROM"><![CDATA[08-NOV-18 05.00.34.298260000 PM]]></COLUMN>
 *     <COLUMN NAME="EXPERT_NO"><![CDATA[758750]]></COLUMN>
 *     <COLUMN NAME="MANDATOR_NO"><![CDATA[100]]></COLUMN>
 *   </ROW>
 *   <ROW>
 *     <COLUMN NAME="CONNECTION_NO"><![CDATA[2517308732]]></COLUMN>
 *     <COLUMN NAME="VAR"><![CDATA[member_login_time]]></COLUMN>
 *     <COLUMN NAME="VALUE"><![CDATA[20181108164224]]></COLUMN>
 *     <COLUMN NAME="VALID_FROM"><![CDATA[08-NOV-18 05.00.34.352730000 PM]]></COLUMN>
 *     <COLUMN NAME="EXPERT_NO"><![CDATA[758750]]></COLUMN>
 *     <COLUMN NAME="MANDATOR_NO"><![CDATA[100]]></COLUMN>
 *   </ROW>
 * </pre>
 * <p>
 * 
 * Obtain data files via Oracle SQLDeveloper:
 * 
 * <ol>
 * <li>Execute Query, e.g.: "SELECT * FROM PERSON PARAM WHERE ROWNUM < 4;"</li>
 * <li>Right click "Query Result" Window.</li>
 * <li>Select "Export"</li>
 * <li>Choose "Format -> XML"</li>
 * <li>Choose "Save As -> Clipboard"</li>
 * <li>Create a file somewhere in your (resources) classpath.</li>
 * <li>Paste the clipboard (<STRG + V>) into the file.</li>
 * <li>In case Oracle SQL Developer created a header with " encoding='UTF8'" correct that to "encoding='UTF-8'" (else you get an exception).</li>
 * </ol>
 * <p>
 * 
 * @author Achim.Westermann@gmx.de
 */
public class XMLResultSetFactorySQLDeveloperSupport extends XMLResultSetFactory
{
    /** ID of the "dialect" the XML export feature of Oracle SQLDeveloper creates. */
	public final static int ORACLE_SQLDEVELOPER_DIALECT = 2;
    
	/** A copy from superclass. Field is needed for output, but private and I did not want to touch original. */
	protected String copyFileName; 
	
	public XMLResultSetFactorySQLDeveloperSupport(final File file)
	{
		super(file);
		this.copyFileName = file.getAbsolutePath();
	}

	public XMLResultSetFactorySQLDeveloperSupport(final String fileName)
	{
		super(fileName);
		this.copyFileName = fileName;
	}

	/**
	 * Compared to {@link XMLResultSetFactory#create(String)} this adds support for 
	 * {@link #ORACLE_SQLDEVELOPER_DIALECT} and dispatches to <code>super</code> when 
	 * that {@link #getDialect()} is not matched. 
	 * 
	 * @see #setDialect(int)
	 */
	@Override
	public MockResultSet create(String id)
	{
		MockResultSet mockResultSet;
		switch(this.getDialect())
		{
			case ORACLE_SQLDEVELOPER_DIALECT :{
				mockResultSet = createSQLDeveloperResultSet(id);
				break;
			}
			default :
			{
				mockResultSet = super.create(id);
			}
		}
		return mockResultSet;
	}
	
	   
    /**
	 * Return a MockResultSet with proper column names and rows based on the XML <code>Document</code>.
	 * <p>
	 * Basically this is the same "dialect" as {@link XMLResultSetFactory#SYBASE_DIALECT} with the following changes: 
	 * <ul>
	 * <li>Nodes for rows are not "row" but "ROW" (uppercase). </li>
	 * <li>Column nodes have the column name in the attribute value of attribute "NAME" (v.s. the column node name is the database column name): <FIRSTNAME ...> --> <COLUMN NAME="FIRSTNAME"..> </li>
	 * </ul>
	 * <p>
	 * <b>Example format:</b>
	 * <RESULTS>
	 *   <ROW>
	 *     <COLUMN NAME="CONNECTION_NO"><![CDATA[2517308732]]></COLUMN>
	 *     <COLUMN NAME="VAR"><![CDATA[chatservice.platformid]]></COLUMN>
	 *     <COLUMN NAME="VALUE"><![CDATA[QDE]]></COLUMN>
	 *     <COLUMN NAME="VALID_FROM"><![CDATA[08-NOV-18 05.00.34.298260000 PM]]></COLUMN>
	 *     <COLUMN NAME="EXPERT_NO"><![CDATA[758750]]></COLUMN>
	 *     <COLUMN NAME="MANDATOR_NO"><![CDATA[100]]></COLUMN>
	 *   </ROW>
	 *   <ROW>
	 *     <COLUMN NAME="CONNECTION_NO"><![CDATA[2517308732]]></COLUMN>
	 *     <COLUMN NAME="VAR"><![CDATA[member_login_time]]></COLUMN>
	 *     <COLUMN NAME="VALUE"><![CDATA[20181108164224]]></COLUMN>
	 *     <COLUMN NAME="VALID_FROM"><![CDATA[08-NOV-18 05.00.34.352730000 PM]]></COLUMN>
	 *     <COLUMN NAME="EXPERT_NO"><![CDATA[758750]]></COLUMN>
	 *     <COLUMN NAME="MANDATOR_NO"><![CDATA[100]]></COLUMN>
	 *   </ROW> 
	 * <p>
	 * 
	 * @return MockResultSet Results read from XML <code>Document</code> in the format Oracle SQL Developer creates.
	 */
	public MockResultSet createSQLDeveloperResultSet(String id)
	{
		MockResultSet resultSet = new MockResultSet(id);
		SAXBuilder builder = new SAXBuilder();
		Document doc = null;
		File fileToParse = getXMLFile();
		if (null == fileToParse)
		{
			throw new RuntimeException("File " + this.copyFileName + " not found.");
		}
		try
		{
			doc = builder.build(fileToParse);
			Element root = doc.getRootElement();
			List<Element> rows = root.getChildren("ROW");
			Iterator<Element> ri = rows.iterator();
			boolean firstIteration = true;
			// <ROW> - iteration START
			while (ri.hasNext())
			{
				// 1 ROW START
				Element cRow = (Element) ri.next();
				List<Element> cRowChildren = cRow.getChildren();
				Iterator<Element> cri = cRowChildren.iterator();
				String[] cRowValues = new String[cRowChildren.size()];
				int curCol = 0;
				
				while (cri.hasNext())
				{
					// 1 CELL START
					Element crValue = cri.next();
					// 1st row: Get column names: 
					if (firstIteration)
					{
						resultSet.addColumn(crValue.getAttributeValue("NAME"));
					}
					
					String value = this.getTrim() ? crValue.getTextTrim() : crValue.getText();
					cRowValues[curCol] = value;
					curCol++;
					// 1 CELL END
				}
				resultSet.addRow(cRowValues);
				firstIteration = false;
				// 1 ROW END
				
			}
			// <ROW> - iteration END
			
		}
		catch (Exception exc)
		{
			throw new NestedApplicationException("Failure while reading from XML file", exc);
		}
		return resultSet;
	}
	
}

**Comment by achimwestermann** [comment]
I better add an attachment. Pasted source looks awful.
[com.mockrunner.jdbc-orcalsqldeveloperformat.zip](https://github.com/mockrunner/mockrunner/files/5186973/com.mockrunner.jdbc-orcalsqldeveloperformat.zip)

**Comment by cemartins** [comment]
Hi Achim, Thanks for your interest.

I'm really sure what this piece of code does. Could you explain a bit more about the functionality that you are proposing?

**Comment by achimwestermann** [comment]
Hi Cemartins, 
mockrunner-jdbc has an interface for factories that produce MockResultSet instances. One mocks the jdbc ResultSet. Most often backed by some test data. 
One example is this one: https://github.com/mockrunner/mockrunner/blob/master/mockrunner-jdbc/src/main/java/com/mockrunner/jdbc/XMLResultSetFactory.java 
BTW: it is not documented very well, which format it needs. 

My contribution is for providing MockResultSets that are backed with files in the format of oracle sql developer (database client tool). You can execute queries in oracle sqldeveloper and then right-click and save those files in an xml format. 

This implementation loads files in this format and allow to create Mock result sets for mockrunner-jdbc. Pretty neat if your companie runs on oracle db and want's to have real-world test-tables / data. 

The javadoc in the attached zip file sources are explaining this too. 

cheers, 
Achim

**Comment by cemartins** [comment]
Sounds cool. But I thought SQL Developer files only stored queries, not query results... no?

**Comment by cemartins** [comment]
I created a branch " achimwestermann_contribution " and added the file you sent. I will test it and merge it, if all is cool.
Thank you!

**Comment by achimwestermann** [comment]
I'll have a look if I can add a test file. Regarding "But I thought SQL Developer files only stored queries, not query results... no?". If you look at the javadoc of the source file, there is a complete step by step guide on how to create the xml files to read.

**Comment by achimwestermann** [comment]
Well, all the other testcases have been commented out because the files cannot be loaded any more. I guess this is because of a redesign of the project architecture? I don't know. I'll try to fix that first.

**Comment by achimwestermann** [comment]
I fixed the existing testcases, it was only file loading routines. But I cannot push the commit. Either I lack permission or the way I cloned (https) is not allowed to push. Should I send a patch? 

![image](https://user-images.githubusercontent.com/352821/94457738-44ce2100-01b5-11eb-9c0d-87d1299dbf3a.png)

**Comment by cemartins** [comment]
Are you trying to push your changes to master? You can't do that unless you belong to the team of mockrunner committers.
I can add you to the team of committers, but that means you will be involved in maintaining the project and reviewing other people's contributions, not just yours. Would you like that?

If not, then the way to go is to fork this repository into your own list of repositories, create a branch there, make your changes and then make a pull request. That will create a pull request in the original repository with your changes, which allows me and the other committers to review them and accept them, if we can't find any problem with them.

This may seem like a bit of a hassle, but it is quite simple. And it is the way git contributions are normally carried out.

Look forward to hearing from you.

**Comment by achimwestermann** [comment]
Nope, I ain't. I am on branch achimwestermann_contribution  

Unfortunately I only have time to do this small work here. I need 2 or 3 lives to do everything I'd like to in this world. 

I don't know, can't you just allow me to commit to that branch, I hate forking. The OS world ends up with thousands of "fake" forks that deterioate search resulsts.

**Comment by cemartins** [comment]
I see your point.... I kind of agree, actually.
So I added you to the team of committers and you should be able to push your branch after you accept the invite.

Thanks a lot for your contribution.

**Comment by cemartins** [comment]
Merges into master.

**Comment by cemartins** [comment]
I canceled the invitation to 'commuters'. After 5 days, I assume you're not interested. Let me know otherwise.

**Comment by achimwestermann** [comment]
Oh, I did not find the time in these 5 days. I tried to push the fixed testcases for the other resultset factories but it did not work without spending more than 5 minutes and other things were pressing.

**Comment by cemartins** [comment]
No worries. I merged your branch into master
